# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            anonymous: ~            
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/index, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/newAdministrador, role: ROLE_ADMIN }
        - { path: ^/editAdministrador, role: ROLE_ADMIN }
        - { path: ^/deleteAdministrador, role: ROLE_ADMIN }
        - { path: ^/showAdministrador, role: ROLE_ADMIN }
        - { path: ^/newHelpDesk, role: ROLE_ADMIN }
        - { path: ^/editHelpDesk, role: ROLE_ADMIN }
        - { path: ^/deleteHelpDesk, role: ROLE_ADMIN }
        - { path: ^/showHelpDesk, role: ROLE_ADMIN }
        - { path: ^/newTecnico, role: ROLE_ADMIN }
        - { path: ^/editTecnico, role: ROLE_ADMIN }
        - { path: ^/deleteTecnico, role: ROLE_ADMIN }
        - { path: ^/showTecnico, role: ROLE_ADMIN }
        #- { path: ^/incidencia, role: ROLE_ADMIN }
        - { path: ^/newIncidencia, role: ROLE_ADMIN }
        - { path: ^/editIncidencia, role: ROLE_ADMIN }
        - { path: ^/deleteIncidencia, role: ROLE_ADMIN }
        - { path: ^/listIncidencia, role: ROLE_ADMIN }
        - { path: ^/showIncidencia, role: ROLE_ADMIN }
        - { path: ^/newEstado, role: ROLE_ADMIN }
        - { path: ^/editEstado, role: ROLE_ADMIN }
        - { path: ^/deleteEstado, role: ROLE_ADMIN }
        #- { path: ^/user, role: ROLE_ADMIN }