<?php

namespace AppBundle\Entity;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\EntityRepository;

/**
 * PersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends EntityRepository implements UserLoaderInterface
{
	/**
	 * {@inheritDoc}
	 * @see \Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface::loadUserByUsername()
	 */	
	public function loadUserByUsername($username)
	{
		return $this->createQueryBuilder('u')
		->where('u.username = :username OR u.email = :email')
		->setParameter('username', $username)
		->setParameter('email', $username)
		->getQuery()
		->getOneOrNullResult();
	}
	public function findAllOrderedByName()
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT p FROM AppBundle:Persona p ORDER BY p.name ASC'
				)
				->getResult();
	}

}
